# Generated by Django 6.0.1 on 2026-01-25 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=16, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('id_type', models.CharField(choices=[('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ("Driver's License", "Driver's License"), ('Voter ID', 'Voter ID')], default='Ghana Card', max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('emergency_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Insurance', 'Insurance'), ('Card', 'Card'), ('Mobile Money', 'Mobile Money')], default='Cash', max_length=50)),
                ('insurance_provider', models.CharField(blank=True, choices=[('NHIS', 'NHIS'), ('Activa', 'Activa'), ('Sunu', 'Sunu'), ('Glico', 'Glico'), ('Enterprise', 'Enterprise'), ('Other', 'Other')], max_length=100, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_flags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
