# Generated by Django 6.0 on 2025-12-12 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('General Consultation', 'General Consultation'), ('Specialist Review', 'Specialist Review'), ('Lab Only', 'Lab Only'), ('Pharmacy Only', 'Pharmacy Only'), ('Vitals Only', 'Vitals Only'), ('Emergency', 'Emergency'), ('Follow-up', 'Follow-up'), ('Procedure', 'Procedure')], default='General Consultation', max_length=100)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pay Later', 'Pay Later (After Service)'), ('Insurance', 'Insurance'), ('Cash', 'Paid Cash'), ('Mobile Money', 'Mobile Money'), ('Card', 'Credit/Debit Card')], default='Pay Later', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Checked In', 'Checked In'), ('Vitals Taken', 'Vitals Taken'), ('In Consultation', 'In Consultation'), ('Awaiting Lab', 'Awaiting Lab'), ('Awaiting Pharmacy', 'Awaiting Pharmacy'), ('Ready for Discharge', 'Ready for Discharge'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Checked In', max_length=50)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('seen_by_doctor_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='visits.visit')),
            ],
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'check_in_time'], name='visits_visi_status_3987b1_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'check_in_time'], name='visits_visi_patient_93b6f4_idx'),
        ),
    ]
