# Generated by Django 6.0.1 on 2026-01-25 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True, null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('physical_examination', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField()),
                ('clinical_plan', models.TextField()),
                ('prescription', models.TextField(blank=True, null=True)),
                ('admit_patient', models.BooleanField(default=False)),
                ('admission_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_done', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
