# Generated by Django 6.0.1 on 2026-01-25 00:46

import django.core.validators
import django.db.models.deletion
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default=inventory.models.generate_item_id, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('LAB', 'Laboratory')], max_length=20)),
                ('current_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_of_measure', models.CharField(choices=[('PCS', 'Pieces'), ('BOX', 'Boxes'), ('BTL', 'Bottles'), ('KIT', 'Kits'), ('TAB', 'Tablets'), ('CAP', 'Capsules'), ('ML', 'Milliliters'), ('GM', 'Grams'), ('TEST', 'Tests')], default='PCS', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'ordering': ['name'],
            },
        ),
    ]
