# Generated by Django 6.0 on 2025-12-20 23:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default='B9AB008C', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('LAB', 'Laboratory')], max_length=20)),
                ('current_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_of_measure', models.CharField(choices=[('PCS', 'Pieces'), ('BOX', 'Boxes'), ('BTL', 'Bottles'), ('KIT', 'Kits'), ('TAB', 'Tablets'), ('CAP', 'Capsules'), ('ML', 'Milliliters'), ('GM', 'Grams'), ('TEST', 'Tests')], default='PCS', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_name_9b5824_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_categor_b07c45_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_expiry__69d012_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_current_9d2479_idx',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='StockAlert',
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
