# Generated by Django 6.0 on 2025-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.CharField(default='EC004DC0', max_length=50, unique=True),
        ),
    ]
