# Generated by Django 6.0.1 on 2026-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
