# Generated by Django 5.2.7 on 2025-11-03 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Clinician', 'Clinician'), ('Lab', 'Lab'), ('Pharmacy', 'Pharmacy'), ('Cashier', 'Cashier'), ('Ultrasound', 'Ultrasound')], max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who registered this staff user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
