# Generated by Django 6.0.1 on 2026-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('Clinician', 'Clinician'), ('Lab', 'Lab'), ('Pharmacy', 'Pharmacy'), ('Phlebotomist', 'Phlebotomist'), ('Ultrasound', 'Ultrasound')], max_length=50),
        ),
    ]
