# Generated by Django 5.2.7 on 2025-11-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
