# Generated by Django 5.2.7 on 2025-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
