# Generated by Django 6.0.1 on 2026-01-25 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=20)),
                ('clinical_indication', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sample Collected', 'Sample Collected'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_lab_orders', to=settings.AUTH_USER_MODEL)),
                ('sample_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_lab_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_data', models.JSONField(help_text='Test results in JSON format')),
                ('interpretation', models.TextField(blank=True)),
                ('abnormal_flags', models.JSONField(blank=True, default=list, help_text='List of abnormal findings')),
                ('status', models.CharField(choices=[('Preliminary', 'Preliminary'), ('Final', 'Final'), ('Corrected', 'Corrected'), ('Cancelled', 'Cancelled')], default='Preliminary', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab.laborder')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_lab_tests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Hematology', 'Hematology'), ('Biochemistry', 'Biochemistry'), ('Parasitology', 'Parasitology'), ('Microbiology', 'Microbiology'), ('Immunology', 'Immunology'), ('Serology', 'Serology'), ('Urinalysis', 'Urinalysis'), ('Hormones', 'Hormones'), ('Coagulation', 'Coagulation'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sample_type', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Stool', 'Stool'), ('Sputum', 'Sputum'), ('Swab', 'Swab'), ('Serum', 'Serum'), ('Plasma', 'Plasma'), ('Other', 'Other')], max_length=100)),
                ('turnaround_time', models.CharField(help_text="Expected TAT (e.g., '2-4 hours')", max_length=100)),
                ('normal_range', models.TextField(blank=True, help_text='Reference range for results')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='lab_labtest_categor_cd0594_idx'), models.Index(fields=['code'], name='lab_labtest_code_3a8bf7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabOrderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lab.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labtest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', 'urgency'], name='lab_laborde_status_8929a4_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'created_at'], name='lab_laborde_patient_625ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['status', 'created_at'], name='lab_labresu_status_47a411_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labordertest',
            unique_together={('order', 'test')},
        ),
    ]
