# Generated by Django 6.0.1 on 2026-01-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='labtest',
            name='lab_labtest_categor_cd0594_idx',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='turnaround_time',
        ),
    ]
