# Generated by Django 6.0.1 on 2026-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_labtest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='parameters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='normal_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
