# Generated by Django 6.0.1 on 2026-01-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_labtest_parameters_alter_labtest_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
